const defaultPrompts = [
  {id:'photo',title:'নীল + অরিজিনাল ড্রেস',category:'Photo',prompt:`Generate a realistic passport-size photo of a man wearing original shirt that photo wear, strictly following the reference image for facial features and pose, face need 100% match with reference image. The background must be Royal Blue, clean, and professional. The final output must be in standard passport photo dimensions (2x2 inches or 51x51 mm) with realistic lighting and sharp details, perfect for official use.`},
  {id:'photo',title:'সাদা + অরিজিনাল ড্রেস',category:'Photo',prompt:`Generate a realistic passport-size photo of a man wearing original shirt that photo wear, strictly following the reference image for facial features and pose, face need 100% match with reference image. The background must be plain white, clean, and professional. The final output must be in standard passport photo dimensions (2x2 inches or 51x51 mm) with realistic lighting and sharp details, perfect for official use.`},
  {id:'photo',title:'নীল + কালো ব্লেজার',category:'Photo',prompt:`Generate a realistic passport-size photo of a man wearing a black blazer, white shirt, and a solid black tie, strictly following the reference image for facial features and pose, face need 100% match with reference image. The background must be Royal Blue, clean, and professional. The final output must be in standard passport photo dimensions (2x2 inches or 51x51 mm) with realistic lighting and sharp details, perfect for official use.`},
  {id:'photo',title:'সাদা + ব্লেজার',category:'Photo',prompt:`Generate a realistic passport-size photo of a man wearing a black blazer, white shirt, and a solid black tie, strictly following the reference image for facial features and pose, face need 100% match with reference image. The background must be plain white, clean, and professional. The final output must be in standard passport photo dimensions (2x2 inches or 51x51 mm) with realistic lighting and sharp details, perfect for official use.`},
  {id:'photo',title:'নীল + সাদা শার্ট',category:'Photo',prompt:`Generate a realistic passport-size photo of a man wearing a white shirt, strictly following the reference image for facial features and pose, face need 100% match with reference image. The background must be Royal Blue, clean, and professional. The final output must be in standard passport photo dimensions (2x2 inches or 51x51 mm) with realistic lighting and sharp details, perfect for official use.`},
  {id:'photo',title:'নীল + গ্রে কালার শার্ট',category:'Photo',prompt:`Generate a realistic passport-size photo of a man wearing a grey shirt, strictly following the reference image for facial features and pose, face need 100% match with reference image. The background must be Royal Blue, clean, and professional. The final output must be in standard passport photo dimensions (2x2 inches or 51x51 mm) with realistic lighting and sharp details, perfect for official use.`},
  {id:'photo',title:'নীল + সুবজ শার্ট',category:'Photo',prompt:`Generate a realistic passport-size photo of a man wearing a green shirt, strictly following the reference image for facial features and pose, face need 100% match with reference image. The background must be Royal Blue, clean, and professional. The final output must be in standard passport photo dimensions (2x2 inches or 51x51 mm) with realistic lighting and sharp details, perfect for official use.`},
  {id:'photo',title:'নীল + পার্পল শার্ট',category:'Photo',prompt:`Generate a realistic passport-size photo of a man wearing a purple shirt, strictly following the reference image for facial features and pose, face need 100% match with reference image. The background must be Royal Blue, clean, and professional. The final output must be in standard passport photo dimensions (2x2 inches or 51x51 mm) with realistic lighting and sharp details, perfect for official use.`},
  {id:'photo',title:'মহিলা (নীল + অরিজিনাল ড্রেস)',category:'Female Photo',prompt:`Generate a realistic passport-size photo of a woman, strictly following the provided reference image for facial features and pose, face need 100% match with reference image. The woman must wear the exact same outfit as shown in the reference image. The background must be Royal Blue, clean, and professional. The final output must be in Bangladesh passport photo dimensions (45mm x 35mm) with realistic lighting and sharp details, perfect for official use. `},
  {id:'photo',title:'মহিলা (সাদা + অরিজিনাল ড্রেস)',category:'Female Photo',prompt:`Generate a realistic passport-size photo of a woman, strictly following the provided reference image for facial features and pose, face need 100% match with reference image. The woman must wear the exact same outfit as shown in the reference image. The background must be plain white, clean, and professional. The final output must be in Bangladesh passport photo dimensions (45mm x 35mm) with realistic lighting and sharp details, perfect for official use. `},
  {id:'photo',title:'ছবি ব্যাকগ্রাউন্ড',category:'Background Image',prompt:`Generate a realistic photo that strictly following the reference image for facial features and pose, face need 100% match with reference image. The background must be completely removed and add the second image as background that match with the image. The final output must be in standard 4K photo with realistic lighting and sharp details, perfect for official use. Using the uploaded reference image as the highest-priority identity anchor, maintain a 100% exact face match. Keep the exact face shape, jawline, bone structure, eyes, eyebrows, nose, lips, skin texture, forehead, hairline, and natural proportions completely unchanged. Do not beautify, stylize, modify, reinterpret, or smooth facial features. Maintain the same age, expression, and ethnicity.`},
  {id:'OCR EN',title:'ইংরেজি লেখা OCR',category:'OCR',prompt:`Extract all English text from this image with maximum OCR accuracy. Preserve the exact original spelling, words, numbers, punctuation, capitalization, line breaks, headings, paragraphs, tables, and overall reading order. Do not translate, summarize, correct, rewrite, or add anything. If any character or word is unclear, do not guess; write [ [UNCLEAR]] instead. Output only the extracted English text.`},
  {id:'OCR BN',title:'বাংলা লেখা OCR',category:'OCR',prompt:`Extract all Bangla text from this image with maximum OCR accuracy. Preserve the exact original Bangla spelling, words, numbers, punctuation, line breaks, headings, paragraphs, and overall reading order. Do not translate, summarize, correct, rewrite, or add anything. If any character or word is unclear, do not guess; write [[অস্পষ্ট]] instead. Output only the extracted text in proper Unicode Bangla.`},

];

/* Add/edit/remove your default prompts ONLY in this file. 

  {id:'photo',title:'বাংলা লেখা OCR',category:'Photo',prompt:``},
  {id:'photo',title:'বাংলা লেখা OCR',category:'Photo',prompt:``},
  {id:'photo',title:'বাংলা লেখা OCR',category:'Photo',prompt:``},
*/
